config/routes.rb
RottenMangoes::Application.routes.draw do

  resources :movies do
    resources :reviews, only: [:new, :create]
  end

  namespace :admin do
    resources :users
  end
  
  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]
  root to: 'movies#index'

end

  

app/models/movie.rb
class Movie < ActiveRecord::Base


  has_many :reviews
  mount_uploader :image, ImageUploader 

  validates :title,
            presence: true
  validates :director,
            presence: true
  validates :runtime_in_minutes,
            numericality: { only_integer: true }
  validates :description,
            presence: true
  validates :poster_image_url,
            presence: true
  validates :release_date,
            presence: true
  validate :release_date_is_in_the_future

  def review_average
    reviews.sum(:rating_out_of_ten)/reviews.size >= 1
  end

  def self.search(query)
    # where(:title, query) -> This would return an exact match of the query
    where("title like ? OR director like ?", "%#{query}%", "%#{query}%") 
  end

  protected

  def release_date_is_in_the_future
    if release_date.present?
      errors.add(:release_date, "should probably be in the future") if release_date < Date.today
    end
  end

end

app/models/review.rb
class Review < ActiveRecord::Base
  
  belongs_to :user
  belongs_to :movie

  validates :user,
            presence: true

  validates :movie,
            presence: true

  validates :text,
            presence: true

  validates :rating_out_of_ten,
            numericality: { only_integer: true }
  validates :rating_out_of_ten,
            numericality: { greater_than_or_equal_to: 1 }
  validates :rating_out_of_ten,
            numericality: { less_than_or_equal_to: 10 }

end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :reviews

  has_secure_password

  def full_name
    "#{firstname} #{lastname} "
  end
  
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  
  before_filter :restrict_access_admin

  def index
    @users = User.all
  end  

  def new
    @user = User.new
  end

   def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)

    if @user.save
      UserMailer.welcome_email(@user).deliver
      redirect_to admin_users_path, notice: "Welcome aboard, #{@user.firstname}!"
    else
      render :new
    end
  end

  def update
    @user = User.find(params[:id])

    if @user.update_attributes(user_params)
      redirect_to admin_users_path(@user)
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    UserMailer.destroy_email(@user).deliver
    @user.destroy
    redirect_to admin_users_path
  end

  protected

  def user_params
    params.require(:user).permit(:email, :firstname, :lastname, :password, :password_confirmation)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  protected

  def restrict_access_admin
    if !current_user.admin
      flash[:alert] = 'Access Denied'
      redirect_to root_path
    end
  end

  def restrict_access
    if !current_user
      flash[:alert] = 'You must log in.'
      redirect_to new_session_path
    end
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

  def index
    @movies = Movie.all
    if params[:search]
      @movies = Movie.search(params[:search]).order("created_at DESC")
    else
      @movies = Movie.order("created_at DESC")
    end
  end
  

  def show
    @movie = Movie.find(params[:id])
  end

  def new
    @movie = Movie.new
  end

  def edit
    @movie = Movie.find(params[:id])
  end

  def create
    @movie = Movie.new(movie_params)

    if @movie.save
      redirect_to movies_path, notice: "#{@movie.title} was submitted successfully!"
    else
      render :new
    end
  end

  def update
    @movie = Movie.find(params[:id])

    if @movie.update_attributes(movie_params)
      redirect_to movie_path(@movie)
    else
      render :edit
    end
  end

  def destroy
    @movie = Movie.find(params[:id])
    @movie.destroy
    redirect_to movies_path
  end

  protected


  def movie_params
    params.require(:movie).permit(
      :title, :release_date, :director, :runtime_in_minutes, :poster_image_url, :description, :image
      )
  end
  
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  before_filter :restrict_access
  before_filter :load_movie

  def new
    @review = @movie.reviews.build
  end

  def create
    @review = @movie.reviews.build(review_params)
    @review.user_id = current_user.id

    if @review.save
      redirect_to @movie, notice: "Review created successfully"
    else
      render :new
    end
  end

  protected

  def load_movie
    @movie = Movie.find(params[:movie_id])
  end

  def review_params
    params.require(:review).permit(:text, :rating_out_of_ten)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email])

    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to movies_path, notice: "Welcome back, #{user.firstname}!"
    else
      flash.now[:alert] = "Log in failed..."
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to movies_path, notice: 'Adios!'
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      UserMailer.welcome_email(@user).deliver
      session[:user_id] = @user_id
      redirect_to movies_path, notice: "Welcome aboard, #{@user.firstname}!"
    else
      render :new
    end

  end

  protected

  def user_params
    params.require(:user).permit(:email, :firstname, :lastname, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper

  def formatted_date(date)
    date.strftime("%b %d, %Y")
  end

end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_form.html.erb
<%= form_for [:admin, @user] do |f| %>
<% if @user.errors.any? %>
<div>
  <%= pluralize(@user.errors.count, "error") %> prevented the account from being created:
  <ul>
    <% @user.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>
<div col-md-6 col-md-offset-3>
  <div class="form-style">
    <div>
      <%= f.label "email" %><br>
      <%= f.text_field "email" %>
    </div>
    <div>
      <%= f.label "firstname", "First Name" %><br>
      <%= f.text_field "firstname" %>
    </div>
    <div>
      <%= f.label "lastname", "Last Name" %><br>
      <%= f.text_field "lastname" %>
    </div>
    <div>
      <%= f.label "password" %><br>
      <%= f.password_field "password" %>
    </div>
    <div>
      <%= f.label "password_confirmation", "Password Confirmation" %><br>
      <%= f.password_field "password_confirmation" %>
    </div>
    <div><%= f.submit "Submit", class: "btn btn-primary", id: "signup-submit-btn"  %></div>
  </div>
</div>

<% end %>

app/views/admin/users/edit.html.erb
<% @body_class = "admin"%>
<h1 class="new-user-hdr">Admin Edit User</h1>
<%= render 'form' %>

app/views/admin/users/index.html.erb
<% @body_class = "admin" %>
<h1 class="new-user-hdr">List of all Users</h1>
  <div class="admin-create-user">
    <%= link_to "Create New User", new_admin_user_path %>
  </div>
  <% @users.each do |user| %>
  <div class="admin-list-users">
    <%= user.full_name %> /
    <%= user.email %> /
    <%= user.admin %> /
    <%= link_to "Edit", edit_admin_user_path(user) %> / <%= link_to "Delete", admin_user_path(user), method: :delete, confirm: "You sure?" %>
  </div>
  <% end %>

app/views/admin/users/new.html.erb
<% @body_class = "admin"%>
<h1 class="new-user-hdr">Admin Create User</h1>
<%= render 'form' %>

app/views/layouts/_footer.html.erb
<!-- <footer>
  <small>
    <#% if current_user %>
    Signed in as <%= current_user.full_name %> (<#%= link_to "Log out", session_path("current"), method: :delete %>)
    <#%= link_to "Admin", admin_users_path %> 
    <#% else %>
    <#%= link_to "Log In", new_session_path %> | <#%= link_to "Sign Up", new_user_path %>
    <#% end %>
  </small>
</footer> -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RottenMangoes</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">

  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
  <link href='http://fonts.googleapis.com/css?family=Ubuntu:400,700' rel='stylesheet' type='text/css'>

  <%= csrf_meta_tags %>
</head>

<body class="<%= @body_class %>">
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand", id="rtn-mngs-hdr" >Rotten Mangoes</a>
      </div>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <!-- <input type="text" class="form-control" placeholder="Search"> -->
          <%= form_tag(movies_path, :method => "get") do %>
          <%= text_field_tag :search, params[:search], class:"search-input" %>
          <% end %>
        </div>
        <button type="submit" class="btn btn-primary", id="search-btn" >Search</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
      <% if current_user %>
           <%= link_to "Log out", session_path("current"), class:"btn btn-primary", id:"login-out-btn", method: :delete %>
         <%= link_to "Admin", admin_users_path, class: "btn btn-primary", id:"admin-btn" %>
         <% else %>
          <%= link_to "Log In", new_session_path, class: "btn btn-primary", id:"login-out-btn" %>
          <%= link_to "Sign Up", new_user_path, class: "btn btn-primary", id:"signup-btn" %>
     </li>
   </ul>

   <% flash.each do |key, value| %>
    <% content_tag(:div, value) %>
    <% end %>

   <% end %>
 </div><!-- /.navbar-collapse -->
</div><!-- /.container-fluid -->
</nav>
<div class="container">
  <%= yield %>
</div>
<%#= render 'layouts/footer' %>
</body>
</html>

app/views/movies/_form.html.erb
<h1 class="new-movie-hdr">Add Movie</h1>
<%= form_for @movie do |f| %>
<% if @movie.errors.any? %>
<div>
  <%= pluralize(@movie.errors.count, "error") %> prevented this movie from being submitted:
  <ul>
    <% @movie.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>
<div class="col-sm-6">
  <div class="form-style">
    <div class="new-font-style">
      <%= f.label "title" %><br>
      <%= f.text_field "title" %>
    </div>
    <div class="new-font-style" id="new-release-date">
      <%= f.label "release_date" %><br>
      <%= f.date_field "release_date" %>
    </div>
    <div class="new-font-style" id="new-director">
      <%= f.label "director" %><br>
      <%= f.text_field "director" %>
    </div>
    <div class="new-font-style" id="new-runtime">
      <%= f.label "runtime_in_minutes" %><br>
      <%= f.number_field "runtime_in_minutes" %>
    </div>
    <div class="new-movie-choose-file"> 
      <%= f.file_field :image %>
    </div>
    <!-- <div class="new-font-style" id="new-poster-image">
      <%#= f.label "poster_image_url" %><br>
      <%#= f.text_field "poster_image_url" %>
    </div> -->
  </div>
</div>
<div class="col-sm-6">
  <div class="form-style">
    <div class="new-font-style">
      <%= f.label "description" %><br>
      <%= f.text_area "description" %>
    </div>
    <div class="new-font-style">
      <%= f.submit "Submit", class: "btn btn-primary", id: "new-submit" %> 
    </div>
  </div>
</div>
<% end %>

app/views/movies/edit.html.erb
<%= render 'form' %>

app/views/movies/index.html.erb
<% @body_class = "index" %>

<div class="row">
  <% @movies.each do |movie| %>
  <div class= "col-sm-4">
    <%= image_tag movie.image, class: "movie-img img-responsive" %>
    <%#= link_to image_tag(movie.poster_image_url, :class => "movie-img img-responsive"), movie_path(movie) %>
  </div>
  <div class= "col-sm-8 desc-movie">
    <h2 class="movie-title"><%= link_to movie.title, movie_path(movie) %></h2>
    <h3 class="release-date">Release Date: <%= formatted_date(movie.release_date) %></h3>
    <h4 class="director">Director: <%= movie.director %> | <%= movie.runtime_in_minutes %> minutes</h4>
    <p class="description"><%= movie.description %></p>
  </div>
  <% end %>
</div>

app/views/movies/new.html.erb
<%= render 'form' %>

app/views/movies/show.html.erb
<% @body_class = "show" %>
<h1 id="rotten-mangoes-hdr">Rotten Mangoes</h1>
<div class="row">
  <div class="col-sm-4">
    <%= image_tag @movie.image, :class => "movie-image img-responsive" %>
    <%#= link_to image_tag(@movie.poster_image_url, :class => "movie-img img-responsive"), movie_path(@movie) %>
  </div>
  <div class="col-sm-8">
    <h2 class="movie-title"><%= @movie.title %> <%= link_to "Edit", edit_movie_path(@movie), class: "btn btn-primary", id: "show-edit-btn" %><%= link_to "Delete", movie_path(@movie), class: "btn btn-primary", id: "show-delete-btn", method: :delete, confirm: "You sure?" %></h2>
    <h3 class="release-date">Release Date: <%= formatted_date(@movie.release_date) %></h3>
    <h4 class="director">Dir. <%= @movie.director %> | <%= @movie.runtime_in_minutes %> minutes</h4>
    <p class="description"><%= @movie.description %></p> 
  </div>


  <h3 class="review-hdr">Reviews of <em><%= @movie.title %></em></h3>
  <% if current_user %>
  <% @movie.reviews.each do |review| %>
  <p class="review-txt"><%= review.text %><small>- <%= review.user.full_name %></small></p>
  <p class="review-rating">Rating: <%= review.rating_out_of_ten %>/10</p>
  <% end %>
  <p class="review-msg"><%= link_to "Write a review!", new_movie_review_path(@movie) %></p>
  <% else %>
  <p class="login" id="login-msg" >Please <%= link_to "log in", new_session_path %> to see reviews and add your own.</p> 
  <% end %>
  <div class="show-return-btn">
    <%= link_to "Back to all movies", movies_path, class: "btn btn-primary", id:"back-to-index" %>
  </div>

app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>

app/views/reviews/new.html.erb
<%= link_to "Back to movie", movie_path(@movie) %><br/>

<h2>Write a review of <em><%= @movie.title %></em>.</h2>

<%= form_for([@movie, @review]) do |f| %>
<% if @review.errors.any? %>
<div>
  <%= pluralize(@review.errors.count, "error") %> prevented the review from being saved:
  <ul>
    <% @review.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div>
  <%= f.label "text" %><br>
  <%= f.text_area "text" %>
</div>
<div>
  <%= f.label "rating_out_of_ten" %><br>
  <%= f.number_field "rating_out_of_ten" %>
</div>
<div><%= f.submit "Submit" %></div>
<% end %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<% @body_class = "user-new" %>
<h1 class="new-user-hdr">Sign Up</h1>
<%= form_for @user do |f| %>
<% if @user.errors.any? %>
<div>
  <%= pluralize(@user.errors.count, "error") %> prevented the account from being created:
  <ul>
    <% @user.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>
<div col-md-6 col-md-offset-3>
  <div class="form-style">
    <div>
      <%= f.label "email" %><br>
      <%= f.text_field "email" %>
    </div>
    <div>
      <%= f.label "firstname", "First Name" %><br>
      <%= f.text_field "firstname" %>
    </div>
    <div>
      <%= f.label "lastname", "Last Name" %><br>
      <%= f.text_field "lastname" %>
    </div>
    <div>
      <%= f.label "password" %><br>
      <%= f.password_field "password" %>
    </div>
    <div>
      <%= f.label "password_confirmation", "Password Confirmation" %><br>
      <%= f.password_field "password_confirmation" %>
    </div>
    <div><%= f.submit "Submit", class: "btn btn-primary", id: "signup-submit-btn"  %></div>
  </div>
</div>

<% end %>